# For Windows based CI

environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - BUILD_NAME: py27-unit
      PYTHON: "C:\\Python27"
    - BUILD_NAME: py34-unit
      PYTHON: "C:\\Python34"
    - BUILD_NAME: py35-unit
      PYTHON: "C:\\Python35"
    - BUILD_NAME: py36-unit
      PYTHON: "C:\\Python36"

    - BUILD_NAME: py27-lint
      PYTHON: "C:\\Python27"
    - BUILD_NAME: py36-lint
      PYTHON: "C:\\Python36"

    - BUILD_NAME: py27-docs
      PYTHON: "C:\\Python27"
    - BUILD_NAME: py36-docs
      PYTHON: "C:\\Python36"

    - BUILD_NAME: py27-acceptance-ghdl
      PYTHON: "C:\\Python27"

    - BUILD_NAME: py36-acceptance-ghdl
      PYTHON: "C:\\Python36"

install:
  - "git submodule update --init --recursive"
  - "%PYTHON%\\python.exe -m pip install tox"
  - "curl -fsSL -o ghdl.zip https://github.com/tgingold/ghdl/releases/download/v0.35/ghdl-0.35-mingw32-mcode.zip"
  - "7z x ghdl.zip -oghdl -y"
  - "set PATH=%PATH%;ghdl/GHDL/v0.35-mingw32-mcode/bin"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -e %BUILD_NAME%"
